name: ${COMPOSE_PROJECT_NAME}-api

services:
  api:
    container_name: ${COMPOSE_PROJECT_NAME}-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${USERS_DATABASE_DIRECTORY}:/api_data
      - ${OPENALEX_ANALYSIS_CACHE_PATH}:/openalex_analysis_cache
    ports:
      - ${API_PORT}:8000
    environment:
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ACCESS_TOKEN_EXPIRE_HOURS=${ACCESS_TOKEN_EXPIRE_HOURS}
      - PROJECTS_PERSISTENCE_TIME_HOURS=${PROJECTS_PERSISTENCE_TIME_HOURS}
      - LATEX_MAIN_FILE_URL=${LATEX_MAIN_FILE_URL}
      - LATEX_BIBLIO_FILE_URL=${LATEX_BIBLIO_FILE_URL}
      - LATEX_TEMPLATE_URL=${LATEX_TEMPLATE_URL}
      - DEFAULT_MAX_ENTITIES=${DEFAULT_MAX_ENTITIES}
      - SCANR_API_PASSWORD=${SCANR_API_PASSWORD}
      - SCANR_API_URL=${SCANR_API_URL}
      - SCANR_API_USERNAME=${SCANR_API_USERNAME}
      - SCANR_BSO_INDEX=${SCANR_BSO_INDEX}
      - SCANR_PUBLICATIONS_INDEX=${SCANR_PUBLICATIONS_INDEX}
      - CORS_ALLOW_ORIGINS=${CORS_ALLOW_ORIGINS}
      - CORS_ALLOW_CREDENTIALS=${CORS_ALLOW_CREDENTIALS}
      - CORS_ALLOW_METHODS=${CORS_ALLOW_METHODS}
      - CORS_ALLOW_HEADERS=${CORS_ALLOW_HEADERS}
      - THREAD_POOL_MAX_WORKERS=${THREAD_POOL_MAX_WORKERS}
      - API_TITLE=${API_TITLE}
      - API_VERSION=${API_VERSION}
      - USERS_DATABASE_NAME=${USERS_DATABASE_NAME}
      - USERS_DATABASE_DIRECTORY=/api_data
#      - USERS_DATABASE_PATH=/api_data/users.db # Do not change, change the path in the .env file
      - OPENALEX_ANALYSIS_CACHE_PATH=/openalex_analysis_cache
      - OPENALEX_API_KEY=${OPENALEX_API_KEY}
      - OPENALEX_EMAIL=${OPENALEX_EMAIL}

